### ISSUE TITLE
Where is the nswag json schema path？

### ISSUE THREAD

**Issue by hyzx86** [ThisNetWorks/ThisNetWorks.OrchardCore.OpenApi#4]

**Comment by hyzx86** [comment]
When I opened this address, I found that it reported an error
`https://localhost:44300/swagger/index.html`
![image](https://user-images.githubusercontent.com/15613121/85225492-53fa4180-b404-11ea-87a4-dedab2bd8dda.png)

**Comment by hyzx86** [comment]
Solved, I just disabled the OrchardCore function in the test project

**Comment by abbasl7** [comment]
I've installed nuget, enabled all required modules first and then enabled this.
I still get this error. 
Here's a log snippet,
`OrchardCore.Modules.ModularTenantRouterMiddleware: Information: Begin Routing Request
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

System.MissingMethodException: Method not found: 'System.String NJsonSchema.Infrastructure.TypeExtensions.GetDescription(Namotion.Reflection.CachedType, NJsonSchema.Infrastructure.DescriptionAttributeType)'.
   at NSwag.Generation.AspNetCore.Processors.OperationParameterProcessor.ExtendedApiParameterDescription.GetDocumentation()
   at NSwag.Generation.AspNetCore.Processors.OperationParameterProcessor.CreatePrimitiveParameter(OperationProcessorContext context, ExtendedApiParameterDescription extendedApiParameter)
   at NSwag.Generation.AspNetCore.Processors.OperationParameterProcessor.Process(OperationProcessorContext operationProcessorContext)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.RunOperationProcessors(OpenApiDocument document, ApiDescription apiDescription, Type controllerType, MethodInfo methodInfo, OpenApiOperationDescription operationDescription, List`1 allOperations, OpenApiDocumentGenerator swaggerGenerator, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.AddOperationDescriptionsToDocument(OpenApiDocument document, Type controllerType, List`1 operations, OpenApiDocumentGenerator swaggerGenerator, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateForControllers(OpenApiDocument document, IGrouping`2[] apiGroups, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateAsync(ApiDescriptionGroupCollection apiDescriptionGroups)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateAsync(Object serviceProvider)
   at NSwag.AspNetCore.OpenApiDocumentProvider.GenerateAsync(String documentName)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GenerateDocumentAsync(HttpContext context)
   at ThisNetWorks.OrchardCore.OpenApi.Middleware.OrchardCoreOpenApiDocumentMiddleware.GetDocumentAsync(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at OrchardCore.Apis.GraphQL.GraphQLMiddleware.Invoke(HttpContext context, IAuthorizationService authorizationService, IAuthenticationService authenticationService, ISchemaFactory schemaService)
   at OrchardCore.Liquid.ScriptsMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at OrchardCore.Diagnostics.DiagnosticsStartupFilter.<>c__DisplayClass3_0.<<Configure>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at OrchardCore.ContentPreview.PreviewStartupFilter.<>c.<<Configure>b__1_1>d.MoveNext()
--- End of stack trace from previous location ---
   at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext)
   at OrchardCore.Modules.ModularTenantContainerMiddleware.<>c__DisplayClass4_0.<<Invoke>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

Any help on what I could be doing wrong?

**Comment by deanmarcussen** [comment]
You either need to upgrade orchard or use an earlier release of this nuget.

The latest latest version of orchard won’t work as a new version of nswagschema was released to it late this week. This repository will be updated with it soon.

match the version of orchard against the version of this package

**Comment by abbasl7** [comment]
I'm currently using 1.1.0 of both Orchard and this package. Should I try with 1.0.0?

**Comment by deanmarcussen** [comment]
You’ll need a preview version

https://docs.orchardcore.net/en/latest/docs/getting-started/preview-package-source/

https://github.com/ThisNetWorks/ThisNetWorks.OrchardCore.OpenApi/releases/tag/v1.2.0-preview-16608

**Comment by abbasl7** [comment]
Great. That worked. Thank you.
One quick question. The swagger page doesn't show the option to authenticate for "Try it out".
Did I miss something?

**Comment by deanmarcussen** [comment]
See the samples app, you have to register whichever auth options you want to support.

**Comment by hyzx86** [comment]
@deanmarcussen  Why not use  `Swashbuckle.AspNetCore`  , `NSwag.AspNetCore`   always seems that there are some strange problems.

**Comment by deanmarcussen** [comment]
Personally I have always found the opposite :(

But feel free to make your own module
